version : '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
  php:
    # image: php:8.0-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
  mysql:
    image: mysql:8 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  
volumes:
  mysql_data:
